public with sharing class ContactWrapperClass {
    public string lastname;
    public string title;
    public string email;
    public string phone;
    public string conId;
    
    public void setlastname(string lastname)
    {
        this.lastname=lastname;
    }
    public string getlastname()
    {
        return lastname;
    }
    
    public void settitle(string title)
    {
        this.title=title;
    }
    public string gettitle()
    {
        return title;
    }
    
    public void setemail(string email)
    {
        this.email=email;
    }
    public string getemail()
    {
        return email;
    }
    
    public void setphone(string phone)
    {
        this.phone=phone;
    }
    public string getphone()
    {
        return phone;
    }
    
    public void setconId(string conId)
    {
        this.conId=conId;
    }
    public string getconId()
    {
        return conId;
    }

}

